package models.card.monster;

public enum MonsterMode {
<<<<<<< HEAD
    WARRIOR, BEAST_WARRIOR,FIEND,AQUA,BEAST,PYRO,SPELLCASTER, THUNDER,DRAGON,MACHINE,ROCK,INSECT,CYBERSE,FAIRY, SEASERPENT
=======
    WARRIOR,WARRIOR_BEAST,FIEND,AQUA,BEAST,PYRO,SPELLCASTER,THUNDRO,DRAGON,MACHINE,ROCK,INSECT,CYBERSE,FAIRY,SERPENTSEA
>>>>>>> parent of 3b12998 (m)
}
